exclude: '.*\.(TcPOU)'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0  # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.5.0
    hooks:
      # Run the linter.
      - id: ruff
        # `--extend-select I` sorts imports _and_ removes unused ones
        args: [ --fix, --extend-select, I  ]
      # Run the formatter.
      - id: ruff-format
